name: Verify extension
on: [push, pull_request]
permissions:
  contents: read
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-node@v7.0.0
        with:
          node-version: '22'
          cache: npm
      - uses: actions/setup-java@v6.0.1
        with:
          distribution: temurin
          java-version: '17'
      - run: npm ci
      - run: npm run package
      - run: npx tsc --noEmit --noUnusedLocals --noUnusedParameters
